### ISSUE TITLE
Update number of triggers for 2017 ntuples 

### ISSUE THREAD

**Issue by bortigno** [UFLX2MuMu/UFDimuAnalysis#3]
Move this from 6 to 8

https://github.com/UFLX2MuMu/UFDimuAnalysis/blob/9e0a753075673d364a768b3603c58b656107991f/lib/DataFormats.h#L129

**Comment by quantur** [comment]
fixed in commit 1afa5f1a7fcd097f7fc81340e70e31b3ae03b8bd
pull request made.

**Comment by bortigno** [comment]
merge in #8
